require:
  - rubocop-performance
  - rubocop-rspec

AllCops:
  NewCops: enable

Lint/EmptyClass:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Style/ConditionalAssignment:
  Enabled: false

Style/Documentation:
  Enabled: false
